seleniumGrid=true
gridURL=http://localhost:4444/wd/hub
#gridURL=http://localhost:4444/ui/


url = https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index
browser = chrome
username = Admin
password = admin123

implicitWait = 10
explicitWait = 30
